global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9092
- job_name: node_exporter
  static_configs:
  - targets:
    - 134.214.202.27:9100
    - 134.214.202.28:9100
    - 134.214.202.29:9100
    - 134.214.202.30:9100
    - 134.214.202.31:9100
    - 134.214.202.32:9100
    - 134.214.202.33:9100
    - 134.214.202.35:9100
